# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2142654a8f167cb922bdf786dd5161461f4da5520e8e7d5e476560859e2925d2f1c3549551025a2def4ec0cda9f9c5ed3f050f3c975bac516a2c2b99854926f9

test:
  secret_key_base: 1de95c64373de366512f903f3eebe90c09d5729dd87c0f7cfcf132e9fb55e1838287ca843c2db4c3e1a3b838ab8e01f4f446473c5555de25673531597aafc611

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
